name: bayesian-course
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - numpy>=1.26
  - scipy>=1.12
  - matplotlib>=3.8
  - pandas>=2.2
  - arviz>=0.18
  - pip
  - pip:
      - "jax[cpu]>=0.4.30"
